### github action to publish a new CITATION.cff 
##
name: "cff validation"

## Controls when the workflow will run
on:
  push:
    paths:
      - CITATION.cff

  ## Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  validate:
    name: "validate"
    runs-on: ubuntu-latest
    steps:
      - name: Check out a copy of the repository
        uses: actions/checkout@v2

      - name: Validate a CITATION.cff from a subdirectory
        uses: citation-file-format/cffconvert-github-action@2.0.0
        with:
          args: "--infile ./CITATION.cff --validate"
